### ISSUE TITLE
How to configure an exclusive consumer

### ISSUE THREAD

**Issue by vilasmaciel** [LeanKit-Labs/wascally#111]
In my use case I need to connect to a third party's RabbitMQ as an exclusive consumer of a queue. The exclusive property available in the settings JSON establish an "exclusive owner", but thats returns an error because I can't create the queue as it already exists. What i need is to configure an exclusive consumer, and I see that amqp supports that, how can I configure this kind of consumer with this library?

**Comment by derickbailey** [comment]
are you trying to consume from an existing queue, or create a new one?

**Comment by arobson** [comment]
@vilasmaciel - as of right now, wascally doesn't give you a way to exclusively consume a queue your service didn't create. I can add this feature to the `startSubscription` call.

**Comment by vilasmaciel** [comment]
@derickbailey I'm trying to consume from an existing one. 

@arobson I have solved by activating the "exclusive" property in the subscribe method ('src/amqp/queue.js'). It's a temporal workaround until you add this feature. Thanks a lot!

https://github.com/vilasmaciel/wascally/commit/f81d892df82fa4b81d1ce65d64ea0f64629b14cc
