### ISSUE TITLE
Declare a queue as HA

### ISSUE THREAD

**Issue by NRaf** [LeanKit-Labs/wascally#114]
Does Wascally support setting the HA policy on queues (https://www.rabbitmq.com/ha.html)? I've gone through the README and a pass over the code and haven't been able to find anything.

We achieve this in our Java Spring application by setting "x-ha-policy" as "all".

**Comment by arobson** [comment]
@NRaf - as of now, wascally only supports features exposed via AMQP. I don't plan on adding HTTP API call support any time in the immediate future so I recommend setting this via the dashboard and using naming conventions in your queues.
