### ISSUE TITLE
Unable to handle non-JSON messages

### ISSUE THREAD

**Issue by NRaf** [LeanKit-Labs/wascally#116]
I understand that wascally only supports JSON messages, which is fine. The issue, however, is that there doesn't seem to be any way, that I can see, to recover from an incorrectly formatted message.

For example, if I was to publish a message with content 'test' from the admin console, the following is what I see in the logs:
```
wascally.topology info +9ms Declaring queue 'test_queue' on connection 'default' with the options: {"autoDelete":false,"subscribe":true,"x-ha-policy":"all"}```
  wascally.amqp-queue info +266ms Starting subscription test_queue - default
  wascally.amqp-queue info +153ms Unsubscribing from queue test_queue with tag amq.ctag-wzfPg5gCb0g7Y4fIRC0uGy
```

That just keeps going until the process crashes. I've tried attaching an error handler to handler but it never gets called.

Looking through the wacally source, the issue appears to be in queue.js:
```javascript
function subscribe( channelName, channel, topology, messages, options ) {
	var shouldAck = !options.noAck;
	var shouldBatch = !options.noBatch;

	if ( shouldAck && shouldBatch ) {
		messages.listenForSignal();
	}

	log.info( 'Starting subscription %s - %s', channelName, topology.connection.name );
	return channel.consume( channelName, function( raw ) {
		var correlationId = raw.properties.correlationId;
		raw.body = JSON.parse( raw.content.toString( 'utf8' ) );
```

JSON.parse is throwing an exception.

Is there any way to catch this from the front-end so that we can recover from the error?

**Comment by arobson** [comment]
@NRaf - wascally is no longer under active development. [rabbot](https://github.com/arobson/rabbot) actually has support for custom serialization out of the box and even supports more types by default. Hope that's helpful.
