### ISSUE TITLE
Consumer Cancel Notification

### ISSUE THREAD

**Issue by vilmysj** [LeanKit-Labs/wascally#117]
Does Wascally support `Consumer Cancel Notification`?
https://www.rabbitmq.com/consumer-cancel.html

**Comment by arobson** [comment]
@vilmysj - check out [rabbot](https://github.com/arobson/rabbot), it handles them implicitly. As an example, you can go into the dashboard, delete a queue that has bindings and an active subscription and rabbot will log that a consumer cancel took place, re-create the queue, the binding and re-start the subscription.
