### ISSUE TITLE
Wascally does not re-subscribe to manually started subscriptions on reconnection

### ISSUE THREAD

**Issue by arobson** [LeanKit-Labs/wascally#119]
If `subscribe` is set to false on a queue when it's defined, then wascally will not automatically re-establish a subscription to the queue if the connection to Rabbit (or the subscriber channel) is lost.

This leads to unexpected behavior that looks like consumers "just dropping" because wascally will transparently re-establish the connection, exchanges, queues and bindings without issues.

Subscriptions should get automatically re-established regardless of how they were created.

**Comment by arobson** [comment]
This is handled in [`rabbot`](https://github.com/arobson/rabbot).

**Comment by openam** [comment]
Are the changes/additions from [arobson/rabbot](https://github.com/arobson/rabbot) going to make it back into wascally, or are they diverging at this point?

**Comment by arobson** [comment]
@openam they're diverging. For the most part the APIs are compatible, the reason for the divergence is that wascally has very different failure semantics (it tries to recover always from everything). With rabbot, I'm scaling back the "magic" so folks using it need to own how their service behaves in the face of some kinds of failures.
