### ISSUE TITLE
fanout exchange should not require message type or routing key

### ISSUE THREAD

**Issue by derickbailey** [LeanKit-Labs/wascally#122]
It looks like wascally requires either a message type or routing key when using a fanout exchange type. 

I should be able to produce and consume a message without either, when using a fanout type, as the fanout type completely ignores routing keys anyways.

I don't have any demo code at the moment, but I found this in some tests of my Rabbus library. I tried to publish a message with an empty string for the messageType and no routingKey, and it threw an error / didn't publish the message.

**Comment by rhyslbw** [comment]
+1

**Comment by arobson** [comment]
This feature was added to [rabbot](https://github.com/arobson/rabbot), the successor to wascally.
