### ISSUE TITLE
Connection FSM consistency?

### ISSUE THREAD

**Issue by yamii** [LeanKit-Labs/wascally#124]
I'm listening to wascally's connection

```
wascally.connections.default.connection.on( < aquiring | lost | acquired | connected >, handler )
```
When `RabbitMQ Server is online` before I started my gateway `( only holds the Requester objects )`. The state goes to this
`acquired -> connected`

but when 
`RabbitMQ Server is initially offline when I started my gateway.`
The state just shoots of to `acquired` when `RabbitMQ server goes online` and doesn't pass through `connected`

I observe that `connected` is emitted only once so I needed it because I have some initialisation code going while `acquired` is always emitted everytime RabbitMQ server comes online. 

Though I can set a flag to put my initialisation code inside `acquired` handler this maybe an issue ( though low prio ) because the transition of state is not consistent when `RabbitMQ Server` is initially online or offline.

**Comment by arobson** [comment]
@yamii - [rabbot](https://github.com/arobson/rabbot)'s FSMs have been reworked quite a bit. I'm not certain off the top of my head that they would necessarily address this concern, but it's probably worth having a look. Wascally is no longer actively maintained.

**Comment by yamii** [comment]
@arobson thanks! I'll checkout rabbot
