### ISSUE TITLE
Setting a consumer tag

### ISSUE THREAD

**Issue by lgomez** [LeanKit-Labs/wascally#125]
Hello,

Please bare with me as I am learning about Rabbit and Wascally. This question may not make much sense.

I have a number of dynamically-added ephemeral consumers and would like to be able to easily identify them in the management console by setting the consumer tag to something that makes more sense in my domain. Is there a way to set it in Wascally?

This is what I am doing in code to test:
```javascript
var id = 1;  // id is different for each consumer process.
rabbit.configure( {
  connection: {
    user: 'guest',
    pass: 'guest',
    server: [ 'localhost' ],
    port: 5672,
    vhost: '%2f',
  },
  exchanges: [
    {
      name: 'events',
      type: 'fanout',
      autoDelete: true
    },
  ],
  queues: [
    {
      name: 'events-q-' + id,
      autoDelete: true,
      subscribe: true
    },
  ],
  bindings: [
    {
      exchange: 'events',
      target: 'events-q-' + id,
      keys: [ '' ]
    },
  ]
});
// ...
rabbit.handle( 'event', function( msg ) {
  log.info({ event: msg.body }, 'Event received');
  msg.ack();
});

```
Elsewhere:
```javascript
rabbit.publish( 'events', {
  type: 'event',
  body: { message: 'Message ' + Date.now() }
});
```
And this is what I mean by "identify them in the management console"...
![screen shot 2016-03-11 at 1 49 25 pm](https://cloud.githubusercontent.com/assets/20891/13716472/20f1c866-e790-11e5-974b-69eb49b67c03.png)

Thank you!

**Comment by arobson** [comment]
@lgomez I am in the process of replacing wascally with a new library, [rabbot](https://github.com/arobson/rabbot). The API is very similar but they behave differently in terms of how failures are handled. Rabbot sets consumer tags and provides additional connection information to make it easier to determine what process owns which consumers. I don't presently have a feature that would let you control the consumer tag in Rabbot, but I can look into adding something like that in the near future.
