### ISSUE TITLE
Duplicate default handling

### ISSUE THREAD

**Issue by djMax** [LeanKit-Labs/wascally#133]
Seems like this line should go away in favor of the default that's already done in getQueue:

https://github.com/LeanKit-Labs/wascally/blob/edc752b6acc1f3fb2ab151277300300d512de875/src/index.js#L230

**Comment by arobson** [comment]
@djMax - thanks for the notice, if you haven't seen it yet, this lib is no longer being actively maintained but I did make this change in rabbot. Thanks.
