### ISSUE TITLE
Accept a uri from configs

### ISSUE THREAD

**Issue by ryanwilliamquinn** [LeanKit-Labs/wascally#136]
It is convenient to set a uri in configuration, vs explicitly setting host, user, pw, etc.  It is especially nice when using Heroku, since a service like cloudamqp provides its connection info in uri format.  If you end up creating review apps or cloning an app, you wouldn't have to worry about parsing out the uri into individual components.

**Comment by arobson** [comment]
@ryanwilliamquinn - I have added this feature to [rabbot](http://github.com/arobson/rabbot) as of version 1.0.0-11. You can provide a `uri` property on the `connection` and anything not on the URI will get backfilled with the usual defaults. Hope that helps!

**Comment by ryanwilliamquinn** [comment]
Hey, thanks for the feedback.  How is rabbot related to wascally?
