### ISSUE TITLE
force batch ack to process?

### ISSUE THREAD

**Issue by derickbailey** [LeanKit-Labs/wascally#24]
I have a scenario where I stand up and tear down queue handlers on a rather frequent basis. Right now, I have to use a setTimeout function with a delay of at least 500ms before tearing down the handler, otherwise my messages get stuck in the queue as unacknowledged.

is there a way for me to force any batched acks to go through, prior to tearing down my handler? I don't like having this delay in my code... i have no confidence that my timeout will be long enough under heavy load, and I don't want to continue increasing it just to account for that. 

thanks, yo

**Comment by arobson** [comment]
@derickbailey - just letting you know that I haven't forgotten about this. I am just getting back from a vacation and will be looking at this again this week.
