### ISSUE TITLE
What happens when we add many exchanges with the same name? How does this affect our application?

### ISSUE THREAD

**Issue by yamii** [LeanKit-Labs/wascally#27]

**Comment by derickbailey** [comment]
RabbitMQ is fairly intelligent about this. If it finds a queue / exchange / whatever with the same name, it returns the existing one to you. It won't try and re-create the same one again and again.

Something to keep in mind, though, when this happens RabbitMQ won't change the existing exchange / queue definition. The first request to create will determine how it is set up. All subsequent requests will just return what's already there. So, if you need to recreate a queue or exchange with different settings, you will have to remove it from your RabbitMQ topology, first.

As for your application - you could slow the application down a little by constantly making requests to create queues and exchanges. But there shouldn't be any detrimental side effects other than that. Just keep the number of requests to create something down to a minimum and you should be ok.
