### ISSUE TITLE
Safely closing a connection to the message broker

### ISSUE THREAD

**Issue by sauravbiswasiupr** [LeanKit-Labs/wascally#37]
Hi, Is there a way to close the connection when needed by using a function call in this module, akin to what one does in amqlib (e.g conn.close() ). If such a function is not provided, is there any another way to close the connection safely ?

**Comment by derickbailey** [comment]
hi @sauravbiswasiupr 

there's a `close` and a `closeAll` method on the main module, directly. Each of these returns a promise, so you know when the connection is done closing.

```js
wascally.closeAll()
  .then(function(){
    // ... done
  });
```

or if you want to close a named connection, you can use the `close` method with a string name

```js
wascally.close("my-connection")
  .then(function(){
    // ... done
  });
```

**Comment by sauravbiswasiupr** [comment]
@derickbailey , thanks. I managed to figure it out as I looked through the specs folder.

**Comment by arobson** [comment]
Added a section in the README to address this. Sorry for the confusion.
