### ISSUE TITLE
Way to tell how many messages are in the que?

### ISSUE THREAD

**Issue by episodeyang** [LeanKit-Labs/wascally#50]
Hi, 

Is there a way to know how many jobs are in each que? 

I am trying to do some load balancing. When new workers start, I want them to connect to the longest que.

Thanks!

Ge

**Comment by arobson** [comment]
@episodeyang - there isn't presently a way to get this kind of metadata consistently from the AMQP protocol. If you enable the management console, it turns on their HTTP API which you can get all kinds of detailed metadata about the server/cluster from.

Eventually, we would like to add support for getting this in wascally, but it will probably be a bit before that feature gets added.
