### ISSUE TITLE
Is the rabbitmq_consistent_hash_exchange plugin required?

### ISSUE THREAD

**Issue by bclubb** [LeanKit-Labs/wascally#55]
If it's required then it would be useful to have a note about adding the plugin to the server.

`rabbit-plugins enable rabbitmq_consistent_hash_exchange`

If it's not required then mentioning it in the tests section would be helpful for anyone trying out the tests.

**Comment by arobson** [comment]
Hi @bclubb - it's actually in the README that it is required for the tests: https://github.com/LeanKit-Labs/wascally#behavior--integration-tests. I can add the instructions like you suggested when I get time later.
