### ISSUE TITLE
message.ack() not working for requests

### ISSUE THREAD

**Issue by dvideby0** [LeanKit-Labs/wascally#57]
After testing multiple releases we discovered that any build since 0.2.0-8 (February 11th) the reply queue will fill up and show all messages as unacked. Here is the sample code we used to test this. 

**Publisher**

```javascript
var rabbit = require( 'wascally' );
var settings = {
  connection: {
    user: '',
    pass: '',
    server: '127.0.0.1',
    port: 5672,
    vhost: ''
  },
  exchanges:[
    { name: 'snd.1', type: 'topic', persistent:true  }
  ]
};
rabbit.configure( settings ).done( function() {

});
var x = 0;
  setInterval(function(){
    rabbit.request( 'snd.1', {
      routingKey: 'post',
      type: 'snd.1.fb.post',
      body: { count: x }
    }).then(function(final){
      console.log(final.body);
      final.ack();
    });
    console.log(x);
    x ++;
  }, 1000);
```

**Subscriber**

```javascript
var rabbit = require( 'wascally' );
var settings = {
  connection: {
    user: '',
    pass: '',
    server: '127.0.0.1',
    port: 5672,
    vhost: ''
  },
  exchanges:[
    { name: 'snd.1', type: 'topic', persistent:true  }
  ],
  queues:[
    { name:'fb', limit: 500, queueLimit: 1000, subscribe: true, durable: true }
  ],
  bindings:[
    { exchange: 'snd.1', target: 'fb', keys: [ 'post','request' ] }
  ]
};
var handler = rabbit.handle( 'snd.1.fb.post', function( message ) {
  try {
    console.log( message.body );
    message.reply(message.body);
  } catch( err ) {
    message.nack();
  }
} );
rabbit.configure( settings ).done( function() {

} );
```

**Comment by dvideby0** [comment]
It appears to be something in this commit, but I am not sure. Its a rather large commit. https://github.com/LeanKit-Labs/wascally/commit/2fefa6683347bfae9328e8475fe1aa4b5653a9fc

**Comment by arobson** [comment]
@dvideby0 - wow, I'm sorry about this. Thanks so much for all your work tracking this down. I will spend some time this evening trying to figure out where this is broken. I'll update you with what I find.

**Comment by dvideby0** [comment]
Thank you very much. We really appreciate the quick response.

**Comment by arobson** [comment]
@dvideby0 - haven't figured out why yet, but something is preventing the batching mechanism from resolving the ack'd messages. The ack call is definitely marking the messages as acknowledged. If you want to see what I'm seeing:

```bash
DEBUG=wascally* node publisher.js
```

**Comment by arobson** [comment]
@dvideby0 try out 0.2.4 and let me know but this bug should be resolved now. Thanks again for the code to help reproduce the problem.

**Comment by dvideby0** [comment]
I was able to test this morning and it appears to be working great. Thank you very much
