### ISSUE TITLE
Handling graceful termination of a subscriber

### ISSUE THREAD

**Issue by mehcode** [LeanKit-Labs/wascally#60]
```
# 1. setup handlers with rabbit.handle
# 2. configure rabbit

process.on('SIGINT', function() {
  # 3. stop accepting more requests  
  # 4. wait for all requests currently being handled to finish
});
```

How would one accomplish 3 or 4?

**Comment by arobson** [comment]
@mehcode - PR #66 *might* address 3 & 4. I need to read up on this, but I thought that SIGINT could disrupt IO. If that's the case, there's nothing the lib can do in terms of further communications with the broker.

The intended behavior is that calling close will shut everything down in an orderly manner. The connection itself shouldn't close until after all outstanding publish calls have resolved and unack'd messages have been acknowledged. You can see this behavior in the tests by setting DEBUG=wacsally* and watching the logs.

**Comment by mehcode** [comment]
> I need to read up on this, but I thought that SIGINT could disrupt IO.

Nope. This is what [python/celery](https://github.com/celery/celery) does for graceful termination. When SIGINT and SIGTERM are caught the worker returns all messages not being worked on to the queue, stops accepting new messages, and waits (with a configurable timeout) until all tasks currently being worked on are ack'ed before allowing termination.

Now if SIGKILL comes there is nothing we can do. But a normal system / init script / docker restart will use SIGTERM and allow us to be graceful about it.

**Comment by arobson** [comment]
@mehcode yeah, I was remembering the process exit event. As of 0.2.5 you should be safe to do the following:

```js
function shutdown() {
    rabbit.closeAll()
        .then( function() {
            process.exit( 128 );
        } );
}

process.on( 'SIGTERM', shutdown );
process.on( 'SIGINT', shutdown );
```

The closeAll should not resolve until all of the following have happened:

 * all published messages were sent
 * all queue subscriptions have been stopped
 * all messages received have been ack'd/nack'd to the broker
 * the connection and channels have all closed

As of 0.2.4 there is a potential race condition that could occur that would cause the connection to close before all the batch acknowledgements for a queue have resolved.

**Comment by arobson** [comment]
@mehcode - take a look at 0.2.5 - and my previous comment. Let me know if there appear to be issues with the clean-up.

**Comment by mehcode** [comment]
@arobson Just want to drop by and say `0.2.5` works perfectly. :100:  I have something slightly different than the above so that it works under `cluster`:

```js
// Master process
// concurrency is the number of times .fork is called
cluster.on('exit', _.after(concurrency, function(worker) {
  process.exit(128);
}));

function ignore() { }

process.on("SIGTERM", ignore)
process.on("SIGINT", ignore)

// Child processes
let gracefulExit = _.once(function() {
  rabbit.closeAll().then(function() {
    cluster.worker.kill()
  })
})

process.on("SIGTERM", gracefulExit)
process.on("SIGINT", gracefulExit)
```

^ Used in my task lib (which is really just an abstraction over how we use wascally in our projects) -- https://github.com/launchbadge/node-bok

**Comment by rg1220** [comment]
@arobson, Hey curious if `closeAll` or `close` also handles `reply`?

Here is our shutdown code:
```
function shutdown() {
    logger.info('SIGTERM received. Waiting for rabbit to gracefully close.');
    rabbit.closeAll()
        .then(function() {
          logger.info('Rabbit said all messages have been completed.');
          process.exit(128);
        });
  }
  process.on('SIGTERM', shutdown);
  process.on('SIGINT', shutdown);

  //For testing
  setTimeout(function() {
    console.log('Emitting SIGTERM');
    process.emit('SIGTERM');
  }, 5000);
```

Just for testing I was adding a setTimeout inside our `rabbit.handle` callback so that when a message comes in it waits 20 seconds to actually be handled and replied to. I would have expected `rabbit.closeAll()` to resolve once that message was actually handled. However, `rabbit.closeAll()` is resolving immediately and we're exiting our process.

**Comment by rg1220** [comment]
Upon further inspection, I may have misunderstood what it actually waits for. I believe it's waiting until all **queued** `publish`, `ack`, `nack`, `reject` messages/responses have been processed. It's not waiting for received messages to reply.
