### ISSUE TITLE
Feature Request: Add a URL property on the connection object

### ISSUE THREAD

**Issue by mehcode** [LeanKit-Labs/wascally#63]
It'd be nice for logging to show `Connected to amqp://...` and it'd make it easier on the usage code if the connection could remember its connection information.

If you're okay with this I don't mind submitting a PR for it.

**Comment by arobson** [comment]
@mehcode - adding a log statement is fine. The connection does keep connection information. Can you be more specific about what you're trying to accomplish? Wascally already handles things like reconnection and multiple connections. What are you attempting to solve for?

**Comment by mehcode** [comment]
I'm not seeing it then. Apologies. If I have a connection object from `rabbit.connections.default` how do I get at the connection information that was used to connect? I'd like to just log the URI it connected to.

**Comment by arobson** [comment]
@mehcode - PR #66 addresses this. You'll just need to attach to the 'connected' event and the connection object will have a `uri` property.

```js
rabbit.on( 'connected', function( connection ) {
   console.log( connection.uri );
} );
```
