### ISSUE TITLE
How to set connection configuration for heroku?

### ISSUE THREAD

**Issue by rafaeljesus** [LeanKit-Labs/wascally#68]
Hey ya,

Ho do I set wascally connection config via JSON with cloudamqp heroku url?

Cloudamqp heroku ex:
```
CLOUDAMQP_URL: amqp:/blabla:dasddasdsadsadassdfsdf@tiger.cloudamqp.com/djkpghhq
```

Cheers

**Comment by derickbailey** [comment]
Heroku is no different than any other server, if you're using a .json file for the configuration. You only need a json file that you require in to your code. i would change the structure slightly, so you don't have to do anything to manipulate it when you load it.

config.json:

```json
{
  "rabbitmq": {
    "connection": {
      "user": "some username",
      "pass": "some password",
      "server": "tiger.cloudamqp.com",
      "vhost": "vhost name
    }
  }
}
```

then load the file in to your code and use the rabbitmq part

```js
var config = require("./config.json");
var wascally = require("wascally");

wascally.configure(config.rabbitmq).then(function(){
  // run your code here
});
```

I run wascally on Heroku using my EPA module to manage configuration per environment (production vs development, etc) https://github.com/derickbailey/epa but it's basically this setup.

**Comment by carlhoerberg** [comment]
Instead of creating  static file, just URL parse instead:

```
var url = require('url');
var cloudamqp_url = url.parse(process.env.CLOUDAMQP_URL);

var config = {
  connection: {
    server: cloudamqp_url.hostname,
    user: cloudamqp_url.auth.split(":")[0],
    pass: cloudamqp_url.auth.split(":")[1],
    vhost: cloudamqp_url.path.substr(1)
  }
};
```

**Comment by derickbailey** [comment]
@carlhoerberg that's nice! makes it easy to use the environment variable that way. 

@rafaeljesus if you are wanting to use the environment variable like that, you can set it with the heroku command line tools:

```heroku config:set CLOUDAMQ_URL="your connection string here"```

**Comment by rafaeljesus** [comment]
Awesome guys,

@carlhoerberg I like your dynamic approach

@derickbailey yeah your watchmecode helped a lot

I didn't know where vhost was, reading the docs I saw where it is

``
CLOUDAMQP_URL  => amqp://user:pass@server/vhost
``

Thx
