### ISSUE TITLE
How to remove binding from a direct exchange?

### ISSUE THREAD

**Issue by episodeyang** [LeanKit-Labs/wascally#69]
Hi @derickbailey @arobson ,

I am trying to elastically scale my servers. Right now I am trying to use a direct exchange for all chat messages between the servers. When a server become online, I register the new server id, creates a new que with the same id, and binds this que to the direct exchange.

Is there a way to remove this binding when the server leaves?

I guess I can use autoDelete: true. 

Thanks!

**Comment by derickbailey** [comment]
I would use both `autoDelete: true` and `exclusive: true`. Auto delete will remove the queue once all consumers of that queue have disconnected. Exclusive will ensure that no other consumers can connect to that queue to use it. This way you have a queue that can only be used by the consumer that created it, and it will be deleted when that consumer disconnects.

**Comment by derickbailey** [comment]
also - why use a direct exchange here? are you trying to only push specific messages to this queue? maybe a fanout exchange would be better? I don't know your situation, so a direct exchange might be appropriate.

**Comment by episodeyang** [comment]
Thanks @derickbailey ! 

yes, I'm trying to push specific messages to this que. The service I'm trying to build is a chat backend. In my app, I am doing bunch of collaborative stuff. To push notifications to all participants, I need a room abstraction. The room abstraction provides a way for me to store states inside a server instance, and a way to transform incoming messages before broadcasting to all participants. 

The architecture look like the following:
![image](https://www.lucidchart.com/publicSegments/view/5550dd3e-9920-490b-aa03-4ae50a009639/image.jpeg)

What do you think? ^_^
