### ISSUE TITLE
Need examples on setting up connection and ques programmatically (without topology definition)

### ISSUE THREAD

**Issue by episodeyang** [LeanKit-Labs/wascally#71]
Hey @derickbailey 

I hit a snag when I was trying to setup the following. I have some code but couldn't get everything to work. I want to:

1. setup a que
2. bind this que to a exchange that is already setup by some other server instance.
3. attach a event handler to this que

using direct exchange. Some example or a simple pointer will greatly help!

**Comment by derickbailey** [comment]
hey @episodeyang 

Each of the methods to create a queue, exchange and binding return a promise. You'll want to either chain them together or `.all` the queue and exchange before creating the binding.

Before creating the layout, though, you need to have a valid connection. I typically use the `.configure` method just for the connection info, and then run from the promise off of that.

Something like this should work:

```js
var when = require("when");
var wascally = require("wascally");

var config = {
  connection: {
    // ...
  }
};

wascally
  .configure(config)
  .then(buildTopology)
  .then(receiveMessages);

function buildTopology(){
  var q = wascally.addQueue("some.q", { /* options here */ });
  var e = wascally.addExchange("some.ex", "direct", { /* options here */ });

  // wait for both the queue and exchange to be created
  // then bind the two, and return the resulting promise
  return when
    .all([q, e])
    .then(function(){
      return wascally.bindQueue("some.ex", "some.q", ["routing", "keys"]);
    });
}

function receiveMessages(){
  wascally.handle("message.type", function(message){
    console.log(message.body);
    message.ack();
  });

  wascally.startSubscription("some.q");
}
```

You can see this in my Rabbus library, for a real-world example. I've got code like this in each of the message consumers, like the "subscriber" here: https://github.com/derickbailey/rabbus/blob/master/rabbus/lib/pub-sub/subscriber.js#L31-L55

**Comment by episodeyang** [comment]
Thanks @derickbailey ! Yes I did run into errors because the exchange wasn't setup:)

This answer is super helpful! Thanks!
