### ISSUE TITLE
Publish method seems async

### ISSUE THREAD

**Issue by joergd** [LeanKit-Labs/wascally#73]
When I run the following program from the command line - say 10 times, I generate only +- 3 new messages on Rabbit. Meaning that sometimes it appears to close all connections before the message has been published. If I leave off the closeAll() line - and run the program say 10 times, I get 10 new messages on Rabbit.

The amqplib sendToQueue method isn't async - if I were to run the scenario below using all amqplib commands it would also publish 10 messages if I were to run the program 10 times.

    wascally.configure(rabbitConfig).done(function() {
      wascally.publish("somet.ex", {
        routingKey: "some-key",
        type: "msg.t",
        body: {}
      })
      wascally.closeAll()
    })

Am I just misreading the documentation and code - or is there something wrong here?

**Comment by derickbailey** [comment]
publishing w/ wascally is asynchronous, and i ran in to this problem with my sample code a number of times as well. typically what i do for sample code is use a `setTimeout` of half a second to give the message some time to be published. 

in my production systems i've never had an issue with this, because i don't typically shut down connections immediately after publishing a message. 

it would be nice to have a promise come back from the publish, though.

**Comment by joergd** [comment]
Yeah I figured it wouldn't be a problem in production - just been carrying on for now. Just made me a little nervous. Thanks for the answer though. (on that sneaky sidenote though - when will rabbus return promises - or use node-style callbacks - so that I can use it with my generator functions :)

**Comment by derickbailey** [comment]
those are changes i definitely want to make. i built the current API in a bit of a rush, while i was still learning a lot of things about how it worked. haven't had time to change it, but it needs to be done soon.

**Comment by joergd** [comment]
You're a gentleman. Thank you.

**Comment by arobson** [comment]
@joergd @derickbailey - wascally returns a promise from publish thy will resolve once rabbit confirms that the message was received by rabbit (it only guarantees that and nothing else). I will try to update the read me before too long to reflect this and hopefully clear up confusion. 

> Note: sendToQueue is not the same as publishing to exchange and I would recommend avoiding it whenever humanly possible ;)

**Comment by reverentgeek** [comment]
Oooo holy promise hand grenade... thy will be done...

**Comment by derickbailey** [comment]
@arobson oh, nice! i thought i had checked for that returning a promise, previously... i must have missed it. :)

and +1 to avoiding `sendToQueue`. always publish through an exchange!

![image](https://cloud.githubusercontent.com/assets/75190/7963386/0dbe373e-09d8-11e5-98a9-cc78d28d09b6.png)

**Comment by joergd** [comment]
Cool - thanks for the heads up on the sendToQueue - I can see now how it is a lot more flexible to publish to the exchange and let the bindings deal with the rest.
