### ISSUE TITLE
Memory leak on postal.js when using req-res pattern

### ISSUE THREAD

**Issue by gideonairex** [LeanKit-Labs/wascally#74]
## Problem
There was a leak on postal.js on [postal.js/lib/postal.js line 270](https://github.com/postaljs/postal.js/blob/master/lib/postal.js#L270-L281) after benchmarking the http server using wascally as rpc to my services. The problem was that the req-res pattern of wascally uses the messageId as a topic which postal creates a _cache_ base on the topic. The problem with that is that it doesnt serve the purpose of caching it when you know that the topic is unique. 

##### Tools on benchmark:
1. [wrk](https://github.com/wg/wrk) as my http benchmark.
2. [pm2](https://github.com/Unitech/pm2)  to see the memory usage of http server.

##### This is the current memory footprint before tests ( wascally requests are in "api-server" )
![screen shot 2015-06-11 at 9 30 35 am](https://cloud.githubusercontent.com/assets/6386061/8098006/94988c38-101c-11e5-93d0-acbe4f2716dc.png)

##### After running wrk and leaving [ postal.js line 270 ](https://github.com/postaljs/postal.js/blob/master/lib/postal.js#L270) as is. This was the result.
![screen shot 2015-06-11 at 9 38 20 am](https://cloud.githubusercontent.com/assets/6386061/8098080/a24a3e5c-101d-11e5-8a96-6c525d024687.png)

##### Disabling the cache [ postal.js line 270 ](https://github.com/postaljs/postal.js/blob/master/lib/postal.js#L270) making this to false
![screen shot 2015-06-11 at 9 39 25 am](https://cloud.githubusercontent.com/assets/6386061/8098094/c8fabe1e-101d-11e5-953f-6761fe7ba743.png)

## Findings:
1. On _Test A_ it piles up on the memory and slowly hanging up the http server.
2. On _Test B_  It didnt pile up the memory.

Is there way to make wascally pass a reset on cache or disables the cache if its a req-res pattern?

**Comment by arobson** [comment]
@gideonairex - thanks for providing such a thorough write-up and explaining your setup. Can you tell me which version of postal 'npm list postal'? Fortunately the author is a good friend of mine and we can talk through how to resolve this but I know he's done some work in the recent past on issues related to caching.

**Comment by gideonairex** [comment]
@arobson - I am using **wascally@0.2.6** which uses the **postal@1.0.6**. Thanks for your prompt response. Let me know if you need more details.

**Comment by arobson** [comment]
@ifandelse - any simple ways to resolve this?

**Comment by ifandelse** [comment]
@arobson @gideonairex I should be able to investigate this today, but I added a `resolverNoCache` flag to the postal envelope a while back to help prevent unnecessary caching in a similar use case. I'll see if that's something that wascally could take advantage of as well.

**Comment by ifandelse** [comment]
![](https://i.imgflip.com/ms1bg.jpg)

**Comment by gideonairex** [comment]
Thanks @ifandelse!

**Comment by gideonairex** [comment]
![thank-you-so-much](https://cloud.githubusercontent.com/assets/6386061/8120989/fb1716d0-10d7-11e5-85fa-382caa4e504c.jpg)
