### ISSUE TITLE
How to recover/subscribe to unacknowledged messages?

### ISSUE THREAD

**Issue by dirajkumar** [LeanKit-Labs/wascally#76]
Is there any way to either recover the unacknowledged messages and publish back to the queue or subscribe to unacknowledged messages?

**Comment by derickbailey** [comment]
AFAIK, the only way to do this is for the message consumer to a) `nack` the message, or b) disconnect, which will automatically `nack` the message.

if you're stuck in a state where the code has errored and messages are in limbo, you will need to shut down and restart the process to get the message back in to the queue.

**Comment by dirajkumar** [comment]
What's happens if I nack the message? Currently I have a queue with couple of unack messages and to get them back into the queue. I need to do the restart?

**Comment by derickbailey** [comment]
If you nack a message, it will be returned to the end of the line in the queue.

Say a Q has m1, m2 and m3 in that order. If your consumer picks up m1 and then calls `nack` on that message, the Q will now have m2, m3, and m1 in that order. The message has been re-queued, so it will no longer be held by the consumer. It will now be at the back of the line in the queue. 

The only time you should need to restart your consumer process to clear an unacknowledged message, is when the code is stuck and cannot ack or nack the message. This typically means something has crashed, or you had a mis-configured message type handler in wascally. 

If you are dealing with misconfigured message types, or message types that your consumer should not be handling, check the wascally documentation for unhandled messages https://github.com/LeanKit-Labs/wascally#unhandled-messages (and look right above that for error handling)

**Comment by dirajkumar** [comment]
@derickbailey  Thanks a lot for a quick response. I really appreciate you for answering my questions patiently. I'm fairly new this and I'm trying to wrap my head around it. 
So let's says there is Q and with messages m1, m2, m3 and consumer A subscribed to the Q. 
Now consumer gets the m1, m2, m3 since it is subscribed right. Out of the three message m1 is nacked and m2, m3 are acknowledged. m2 and m3 will be remove from the queue and will the consumer A get that m1 message again? If no how do I get it?

**Comment by derickbailey** [comment]
@dirajkumar you're welcome! happy to help when i can. :)

Yeah, in that scenario Consumer A would receive m1 a 2nd time... and 3rd, 4th, 5th, etc. if you keep `nack`ing the same message. so, you have to be careful here. i've seen messages go in to infinite loops by accident, with a consumer nacking them over and over and over again.

If you're looking for a way to prevent Consumer A from receiving that same message over and over again, but you still want to process it somewhere else, look in to dead letter exchanges and `reject` the message so it goes to the dlx. https://www.rabbitmq.com/dlx.html
