### ISSUE TITLE
Reconnections and disconnections

### ISSUE THREAD

**Issue by joergd** [LeanKit-Labs/wascally#77]
Hey there - I'm trying to figure out how to handle reconnecting to rabbit when I lose the connection - I can't see where I tap into any kinds of disconnect events to try and connect again after losing the connection. Is there a preferred way to handle this?

**Comment by alanhoff** [comment]
+1

**Comment by arobson** [comment]
@joergd & @alanhoff - see the PR above. I added explanation of connectivity events (that have been there) to the README.
