### ISSUE TITLE
npm install wascally does not work

### ISSUE THREAD

**Issue by ryandac** [LeanKit-Labs/wascally#81]
Hi,

Installing 0.2.7 or 0.2.6 do not work, whereas installing 0.2.5 will work.

The errors I get when installing are:

 Command failed: git clone --template=/Users/admin/.npm/_git_remotes/_templates --mirror git://github.com/ifandelse/riveter.git /Users/admin/.npm/_git-remotes/git-github-com-ifandelse-riveter-git-c54a5909

Thanks

**Comment by arobson** [comment]
@ryandac are you still having this issue with 0.2.9?
