### ISSUE TITLE
Rabbitmq only sends another message to a queue after if ack/nack/resject earlier message.

### ISSUE THREAD

**Issue by harishbisht8** [LeanKit-Labs/wascally#82]
I have single queue and single consumer.
I have noticed that queue doesnt wait for fist message's ack/nack/resject and send further messages to the consumer.
Is there any way to resolve this problem?

**Comment by derickbailey** [comment]
you can limit the # of messages that a given consumer will process at once, using the "limit" option of the queue:

```js
queues: [{
  name: "some.queue"
  limit: 1
}]
```

This will force the consumer to only process 1 message, and wait until `ack`, `nack`, or `reject` is called on the message before it gets the next one. 

See the docs here: https://github.com/LeanKit-Labs/wascally#channel-prefetch-limits

And the AMQP protocol for "consumer prefetch" here: https://www.rabbitmq.com/consumer-prefetch.html

hope that helps!

**Comment by harishbisht8** [comment]
@derickbailey  i  found the same, and it helped
thanks for your reply
cheers
