### ISSUE TITLE
Channels Limit on Heroku (Cloudamqp)

### ISSUE THREAD

**Issue by dirajkumar** [LeanKit-Labs/wascally#85]
Hi,

We're using the cloudamqp server on heroku and they have a limit of allowing 200 channels for free version. We have around 15 queues which are interacting across 4 dynos to send messages between them. 
Since the channel management is hidden from us. Is there a way to control them? 

--
Thanks
Diraj

**Comment by arobson** [comment]
Hi @dirajkumar - wascally will create channels like this:
1 channel per connection to send topology commands (bind, create, etc)
1 channel per connection for the reply queue
1 channel for each queue defined per connection
1 channel for each exchange defined per connection

If you only have 15 queues defined for those 4 dynos, I would expect to see 68 channels in total across 4 connections.

**Comment by arobson** [comment]
@dirajkumar - as off PR #99, I made changes the prevent wascally from re-creating queues, exchanges or bindings. Several folks using this library were making the same calls (like configure) repeatedly which caused wascally to setup everything again and this caused multiple channels to get established for the topology every time the call was made.

See if upgrading to 0.2.9 resolves this issue for you.
