### ISSUE TITLE
There should be a publish timeout

### ISSUE THREAD

**Issue by joeandaverde** [LeanKit-Labs/wascally#91]
When publishing and RabbitMQ is unavailable there's no way to cancel publishing due to timeout. This could cause lots of pending publishes and potentially cause a DoS on other resources that depend on publishing the message to the RabbitMQ server (http, db transaction, etc).

**Comment by arobson** [comment]
@joeandaverde - I'll have to think about this one. I know exactly what you mean about DoS but there's not a "simple" way to address this that doesn't require a decent amount of effort on the application developer's part.
