### ISSUE TITLE
Question on when channels get closed.

### ISSUE THREAD

**Issue by subbucomity** [LeanKit-Labs/wascally#93]
We have an application which uses wascally for rabbitmq. We have about 7 connections to the server but when there is peak load the number of channels open is around 25000 and they never get closed or released. Do we have do anything in our code to close the channels? Due to this we hit more than 1GB of memory on heroku and our worker dynos stop working until we restart. Any help on debugging this issue would be helpful.

Thanks
Subbu

**Comment by arobson** [comment]
@subbucomity - If I recall correctly, this was the result of having multiple calls to the configuration and setup happening. If this is still an issue, please feel free to re-open it and I'll do what I can to assist.

**Comment by subbucomity** [comment]
Alex, you are correct. This was the result of having multiple calls to the
configuration and setup.

--
Subbu Karuppiah
Comity Designs <http://www.comitydesigns.com> | subbu@comitydesigns.com |
408-772-3221
