### ISSUE TITLE
Upgrade amqplib dependency to v0.4.0

### ISSUE THREAD

**Issue by benjsicam** [LeanKit-Labs/wascally#94]
Upgrade amqplib dependency to v0.4.0

- Node v4.x compatibility
- Bug fixes and enhancements

**Comment by joshrivers** [comment]
Are there any blocking issues on this?

**Comment by arobson** [comment]
@benjsicam & @joshrivers - I'll take a look into doing this over the weekend. Sorry for the delay in responding, just been busy :)
