### ISSUE TITLE
Handler registration against wildcard topics (message types)

### ISSUE THREAD

**Issue by dermidgen** [LeanKit-Labs/wascally#95]
I see https://github.com/postaljs/postal.js is being used underneath to support message handlers and dispatching messages from queues. It would appear that it's a raw pass-thru to `postal.subscribe()` and `postal.publish()`. Therefore, I would assume it should be possible to support postals `*` and `#` based wildcards. See https://github.com/postaljs/postal.js#subscribing-to-a-wildcard-topic-using-

For example, various message types (`job`, `acme.event`, `acme.message.user`, `acme.message.group`) are coming into the queue, `acme.worker`. One would like to be able to handle the various message types a bit more cleanly. Like:

```
rabbit.handle('acme.*', function() { ... });
rabbit.handle('acme.#.user', function() { ... });
rabbit.handle('acme.message.*', function() { ... });
```
Postal provides this functionality, but it does not appear to work when being called through `wascally.handle`.

**Comment by arobson** [comment]
@dermidgen I thought it did work this way. If it isn't, that's a short-coming in my test coverage (oops). I'll try to have a look at this over the weekend and see if I can't fix the issue.

**Comment by arobson** [comment]
@dermidgen - I am currently working on a PR and added an integration test for this specifically which works without modifications to 0.2.8. I'll bump this thread when I've PR'd the changes so you can see the test, but the first argument of handle is passed directly to postal and the messages are routed as I'd expect. Any more details you can provide about your setup might help me better understand what you're seeing. Just to be sure - you're using `#` to be 0+ segments and `*` for 1 segment?

**Comment by dermidgen** [comment]
@arobson Thanks for checking this out. Let me see what I can reproduce on my end.

**Comment by dermidgen** [comment]
@arobson I can't see to get Integration Test suite to run - so I never see the results of those tests. Instead, I see failures
```
 Integration Test Suite
    1) "before all" hook for "should keep queue definition"
    2) "after all" hook for "should keep queue definition"
```

**Comment by dermidgen** [comment]
Okay - using the virtualbox provider from @joseph-onsip (thank you) I do get the integration tests running.  However your new tests for wildcards are failing.

```
      when configuring against a bad connection
        ✓ should fail to connect
  ...

    with wild card type handling
      2) should route all messages correctly
```

**Comment by dermidgen** [comment]
I also see a number of other errors; should I be expecting the test suite to pass in anyway?

I am also not seeing the desired behavior after pointing my local test bed at @arobson:next - meh

**Comment by arobson** [comment]
@dermidgen using the provided vagrant instance, I get 140 passing tests. Are you still running into this issue?

**Comment by arobson** [comment]
It's been a month and I haven't heard back. The tests for this feature pass so I'm closing it until I understand what's not working and can reproduce the issue.
