### ISSUE TITLE
Error: Failed to create exchange 'dead.letters-ex.1' on connection 'default' with 'No endpoints could be reached'

### ISSUE THREAD

**Issue by rkstar** [LeanKit-Labs/wascally#97]
i'm using cloudamqp for my rabbitmq instance, and wascally for the setup, but i'm getting this error every time i try to start my app:
```
W20151022-13:28:49.756(-4)? (STDERR) Error: Failed to create exchange 'dead.letters-ex.1' on connection 'default' with 'No endpoints could be reached'
```
here's my config object:
```
{
    connection: {
      user: username,
      pass: password,
      server: server,
      //port: 5672,
      //timeout: 2000
      vhost: vhost
    },
    exchanges:[
      { name: 'dead.letters-ex.1', type: 'direct' }
    ],
    queues:[
      { name: 'dead.letters-q.1', subscribe: false, durable: false }
    ],
    bindings:[{
      exchange: 'dead.letters-ex.1',
      target: 'dead.letters-q.1',
      keys: ['dead']
    }]
  }
```
it says i have no endpoints, but i'm not sure what that means.  it can't reach cloudamqp?

**Comment by michaelklishin** [comment]
"No endpoints could be reached" means the client could not contact RabbitMQ (or possibly failed to authenticate — although modern clients have [no excuse to not provide a more specific error message](https://www.rabbitmq.com/auth-notification.html)).

**Comment by Shawn-LeanKit** [comment]
Yes, that error generally means that the client could not connect to your server based on the information you provided. Out of curiosity, are you still getting this error when you have the "port" attribute of the config object uncommented out?

**Comment by rkstar** [comment]
FYI a previous setup was using RabbitMQ 3.5.4, this deployment is 3.5.6.
@Shawn-LeanKit i tried uncommenting the port but got the same errors.  i'm not provided with a port at cloudamqp

**Comment by derickbailey** [comment]
you may need to up the timeout when connecting to cloudamqp. add a `timeout: 30000` setting to the connection information. i have had to do that in the past, due to network latency across the interwebs

**Comment by Shawn-LeanKit** [comment]
Thanks @derickbailey! That was going to be my next suggestion haha

**Comment by rkstar** [comment]
jacked it up to 60000 and still no love.  this is going to turn out to be something silly, i can feel it.
i've also tried creating a new rmq instance and i tried using one that has worked previously... both have the same problem.

for sure this is me.  but what?  i will dig through some more config on my end and post when i find it.

**Comment by derickbailey** [comment]
my next guess would be vhost name. if your vhost has a / at the beginning of the name, you need to include it in the vhost setting: `vhost: "/foo"`. if there isn't one in the name, don't include it: `vhost: "foo"`

**Comment by rkstar** [comment]
# SOLVED
#### it was definitely my problem.

i am using meteor for this deployment (which has been working fine).  the difference between this app and others i've used wascally with is that i was trying to set my `MONGO_URL` and `MONGO_OPLOG_URL` in a config file like this:
```
process.env.MONGO_URL="mongodb://....."
process.env.MONGO_OPLOG_URL="mongodb://....."
```
#### meteor didn't like that.
apparently because meteor was upset with my attempt to set the `MONGO_URL` it was blocking wascally from doing its job!
i wrote a short shell script to set the environment vars i need for this app and then run the program, and **it worked!**

### thank you
@michaelklishin @derickbailey @Shawn-LeanKit thank you so much for your attentiveness and SPEEDY suggestions and help.  it made a big difference and drove me toward the solution.  REALLY appreciated.

![thanks](https://cloud.githubusercontent.com/assets/651566/10674946/901686ca-78cb-11e5-9418-7fe55f5b486d.gif)

**Comment by derickbailey** [comment]
:+1: 

glad you got it solved! i've never used meteor... so that would have never crossed my mind :)
